# Generated by Django 5.2 on 2025-09-21 18:36

import django.db.models.deletion
import home.models
import phonenumber_field.modelfields
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('message', models.TextField(max_length=2000, verbose_name='Message')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone number')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, max_length=250, null=True)),
                ('school', models.CharField(blank=True, max_length=250, null=True)),
                ('major', models.CharField(blank=True, max_length=250, null=True)),
                ('minor', models.CharField(blank=True, max_length=250, null=True)),
                ('focus_area', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('description', tinymce.models.HTMLField()),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('role', models.CharField(blank=True, max_length=250, null=True)),
                ('quote', models.CharField(blank=True, max_length=250, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='feedbacks')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('is_image', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('description', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Leadership',
                'verbose_name_plural': 'Leaderships',
            },
        ),
        migrations.CreateModel(
            name='MyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('data', models.CharField(blank=True, max_length=250, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images')),
                ('category', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'MyContact',
                'verbose_name_plural': 'MyContacts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolios')),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('body', tinymce.models.HTMLField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('is_side_project', models.BooleanField(blank=True, null=True)),
                ('for_resume', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=70, null=True)),
                ('technology', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('video_file', models.FileField(upload_to='videos/', validators=[home.models.validate_video_file_extension])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_video', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('biography', tinymce.models.HTMLField(default='Passionate about building clean, scalable software that solves real-world problems.')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes')),
                ('resume_password', models.CharField(blank=True, max_length=255, null=True)),
                ('work', models.FileField(blank=True, null=True, upload_to='work_samples')),
                ('welcome_summary', tinymce.models.HTMLField(default='My passion...')),
                ('intro_summary', tinymce.models.HTMLField(default='Passionate about building clean, scalable solutions.')),
                ('resume_summary', tinymce.models.HTMLField(default='A quick overview of my experience, skills, and education.')),
                ('academic_projects_summary', tinymce.models.HTMLField(default='Projects built during my studies, focused on applying core concepts.')),
                ('side_projects_summary', tinymce.models.HTMLField(default='Independent work exploring new tools and solving real problems.')),
                ('contact_summary', tinymce.models.HTMLField(default='Let’s connect — I’m open to opportunities, ideas, or questions.')),
                ('courses', models.ManyToManyField(blank=True, to='home.course')),
                ('educations', models.ManyToManyField(blank=True, to='home.education')),
                ('experiences', models.ManyToManyField(blank=True, to='home.experience')),
                ('leaderships', models.ManyToManyField(blank=True, to='home.leadership')),
                ('links', models.ManyToManyField(blank=True, to='home.mycontact')),
                ('projects', models.ManyToManyField(blank=True, to='home.portfolio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='profiles',
            field=models.ManyToManyField(related_name='all_projects', to='home.profile'),
        ),
        migrations.AddField(
            model_name='mycontact',
            name='profiles',
            field=models.ManyToManyField(related_name='all_links', to='home.profile'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='profiles',
            field=models.ManyToManyField(related_name='all_leaderships', to='home.profile'),
        ),
        migrations.AddField(
            model_name='experience',
            name='profiles',
            field=models.ManyToManyField(related_name='all_experiences', to='home.profile'),
        ),
        migrations.AddField(
            model_name='education',
            name='profiles',
            field=models.ManyToManyField(related_name='all_educations', to='home.profile'),
        ),
        migrations.AddField(
            model_name='course',
            name='profiles',
            field=models.ManyToManyField(related_name='all_courses', to='home.profile'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='logos')),
                ('rating', models.IntegerField(blank=True, default=4, null=True)),
                ('is_key_skill', models.BooleanField(default=False)),
                ('is_hard_skill', models.BooleanField(default=False)),
                ('is_soft_skill', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=70, null=True)),
                ('profiles', models.ManyToManyField(related_name='all_skills', to='home.profile')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='home.skill'),
        ),
    ]
