# Generated by Django 5.2 on 2025-06-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
