# Generated by Django 3.0.8 on 2020-08-13 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_summarizer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Summarizer',
            new_name='SummarizerApp',
        ),
    ]
