# Generated by Django 5.2 on 2025-06-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_resume_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='technology',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
