# Generated by Django 3.1.4 on 2021-12-21 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200813_0502'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SummarizerApp',
        ),
    ]
