# Generated by Django 5.2 on 2025-06-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_portfolio_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='for_resume',
            field=models.BooleanField(default=False),
        ),
    ]
