# Generated by Django 5.2 on 2025-08-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_portfolio_for_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
