# Generated by Django 5.2 on 2025-08-24 00:43

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_experience_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='academic_projects_summary',
            field=tinymce.models.HTMLField(default='Projects built during my studies, focused on applying core concepts.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_summary',
            field=tinymce.models.HTMLField(default='Let’s connect — I’m open to opportunities, ideas, or questions.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='intro_summary',
            field=tinymce.models.HTMLField(default='Passionate about building clean, scalable solutions.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_summary',
            field=tinymce.models.HTMLField(default='A quick overview of my experience, skills, and education.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='side_projects_summary',
            field=tinymce.models.HTMLField(default='Independent work exploring new tools and solving real problems.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=tinymce.models.HTMLField(default='Passionate about building clean, scalable software that solves real-world problems.'),
        ),
    ]
