# Generated by Django 5.2 on 2025-08-24 01:34

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_profile_academic_projects_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='welcome_summary',
            field=tinymce.models.HTMLField(default='My passion...'),
        ),
    ]
