# Generated by Django 4.0 on 2021-12-22 17:09

import datetime
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_contact_options_remove_contact_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='0000000000', max_length=10, verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
