# Generated by Django 4.0 on 2021-12-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_education_delete_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='leaderships',
            field=models.ManyToManyField(blank=True, to='home.Education'),
        ),
    ]
