# Generated by Django 4.0 on 2021-12-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_profile_leaderships'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='educations',
            field=models.ManyToManyField(blank=True, to='home.Education'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='leaderships',
            field=models.ManyToManyField(blank=True, to='home.Leadership'),
        ),
    ]
