# Generated by Django 4.0 on 2021-12-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_education_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
