# Generated by Django 4.0 on 2021-12-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_portfolio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='year',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
