# Generated by Django 4.0 on 2021-12-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_portfolio_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.CharField(blank=True, default="It's coming soon!", max_length=1000, null=True),
        ),
    ]
