# Generated by Django 4.0 on 2021-12-25 04:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_profile_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
