# Generated by Django 4.0 on 2022-01-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_profile_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=2000, verbose_name='Message'),
        ),
    ]
