# Generated by Django 4.0.1 on 2022-01-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_profile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='rating',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
