# Generated by Django 4.0.1 on 2022-01-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_link_profile_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=250, null=True, verbose_name='Subject'),
        ),
    ]
