# Generated by Django 4.0.1 on 2022-01-19 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_link_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='MyContacts',
        ),
    ]
