# Generated by Django 4.0.1 on 2022-01-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_rename_link_mycontacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycontacts',
            options={'ordering': ['name'], 'verbose_name': 'MyContact', 'verbose_name_plural': 'MyContacts'},
        ),
    ]
