# Generated by Django 4.0.1 on 2022-01-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_remove_mycontacts_url_mycontacts_data_or_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycontacts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
