# Generated by Django 4.0.1 on 2022-01-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_mycontacts_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycontacts',
            old_name='data_or_link',
            new_name='data',
        ),
        migrations.AddField(
            model_name='mycontacts',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='logos'),
        ),
        migrations.AddField(
            model_name='mycontacts',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
