# Generated by Django 4.0.1 on 2022-01-19 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_rename_data_or_link_mycontacts_data_mycontacts_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycontacts',
            old_name='link',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='mycontacts',
            name='image',
        ),
    ]
