# Generated by Django 4.0.1 on 2022-01-20 18:58

import ckeditor.fields
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
