# Generated by Django 4.0.1 on 2022-01-20 19:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_alter_contact_phone_alter_leadership_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
