# Generated by Django 4.0.1 on 2022-01-20 19:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_alter_profile_biography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='body',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
