# Generated by Django 4.0.1 on 2022-01-28 02:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_alter_contact_phone_alter_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
