# Generated by Django 4.0.1 on 2022-01-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_portfolio_body_alter_portfolio_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='technology',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
