# Generated by Django 4.0.1 on 2022-03-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_portfolio_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.ImageField(blank=True, null=True, upload_to='resumes'),
        ),
    ]
