# Generated by Django 4.0.1 on 2023-05-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_alter_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='work',
            field=models.FileField(blank=True, null=True, upload_to='work_samples'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes'),
        ),
    ]
