# Generated by Django 4.0.1 on 2023-05-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_alter_mycontacts_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycontacts',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
