# Generated by Django 4.0.1 on 2024-03-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_alter_mycontacts_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='major',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='minor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
