# Generated by Django 5.1.1 on 2024-10-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_remove_education_focus_area_remove_education_minor'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='focus_area',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='minor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
