# Generated by Django 5.1.1 on 2024-10-11 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_education_focus_area_education_minor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='major',
        ),
    ]
