# Generated by Django 5.1.1 on 2024-10-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_remove_education_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='major',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
